// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeautyCenter_.Net_Angular.Models;

[PrimaryKey("UserId", "PackageId")]
[Table("PackageUser")]
public partial class PackageUser
{
    [Key]
    public int UserId { get; set; }

    [Key]
    public int PackageId { get; set; }

    public DateTime Date { get; set; }

    [ForeignKey("PackageId")]
    [InverseProperty("PackageUsers")]
    public virtual Package Package { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("PackageUsers")]
    public virtual Userr User { get; set; }
}