// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeautyCenter_.Net_Angular.Models;

[Table("Service")]
public partial class ServiceResponse
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Category { get; set; }

    [InverseProperty("Service")]
    public virtual ICollection<UserService> ?UserServices { get; set; } 


    public virtual ICollection<PackageService>? PackageServices { get; set; }
}