// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeautyCenter_.Net_Angular.Models;

[Table("Userr")]
public partial class Userr
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string BankAccount { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<PackageUser> PackageUsers { get; set; } = new List<PackageUser>();

    [InverseProperty("User")]
    public virtual ICollection<UserService> UserServices { get; set; } = new List<UserService>();
}