// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeautyCenter_.Net_Angular.Models;

[PrimaryKey("UserId", "ServiceId")]
public partial class UserService
{
    [Key]
    public int UserId { get; set; }

    [Key]
    public int ServiceId { get; set; }

    public DateTime? Date { get; set; }

    [ForeignKey("ServiceId")]
    [InverseProperty("UserServices")]
    public virtual ServiceResponse Service { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserServices")]
    public virtual Userr User { get; set; }
}